"""initial migration

Revision ID: 94d3918ba3d8
Revises: 
Create Date: 2018-05-22 23:48:24.548009

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

from blog import db


# revision identifiers, used by Alembic.
revision = '94d3918ba3d8'
down_revision = None
branch_labels = None
depends_on = None


def set_lean():
    sql = '''
        INSERT INTO user(email, nickname, password, create_time, update_time)
            VALUES('{0}', '{1}', '{2}', '{3}', '{4}')
    '''.format('heymanlean@gmail.com', 'Lean', 'bin1307831356', datetime.now(), datetime.now())
    db.engine.execute(sql)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=24), nullable=True),
        sa.Column('nickname', sa.String(length=16), nullable=True),
        sa.Column('password', sa.String(length=16), nullable=False),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.Column('update_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('article',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('user_id', sa.SmallInteger(), nullable=True),
        sa.Column('create_time', sa.DateTime(), nullable=True),
        sa.Column('update_time', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    set_lean()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
