"""modify article table

Revision ID: fc13c11a6044
Revises: 94d3918ba3d8
Create Date: 2018-06-06 08:21:08.225189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc13c11a6044'
down_revision = '94d3918ba3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('html', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'status')
    op.drop_column('article', 'html')
    # ### end Alembic commands ###
